spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/test;
    url: jdbc:mysql://127.0.0.1:3306/user?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: root
    password: Eksnrdl!1
    driver-class-name: com.mysql.cj.jdbc.Driver


logging:
  level:
    com.bookflex: debug

jwt:
  header: Authorization
  secret: fieldproject
  token-validity-in-seconds: 3600000

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.bookflex.backend.dto